# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 503)
        self.CentralWidget = QtWidgets.QWidget(MainWindow)
        self.CentralWidget.setObjectName("CentralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CentralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.CentralWidget)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_passgen = QtWidgets.QWidget()
        self.tab_passgen.setObjectName("tab_passgen")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_passgen)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_passgen_password = QtWidgets.QLabel(self.tab_passgen)
        self.label_passgen_password.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_passgen_password.setObjectName("label_passgen_password")
        self.verticalLayout_2.addWidget(self.label_passgen_password)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_passgen)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox_passgen = QtWidgets.QSpinBox(self.tab_passgen)
        self.spinBox_passgen.setMinimum(1)
        self.spinBox_passgen.setMaximum(999)
        self.spinBox_passgen.setProperty("value", 8)
        self.spinBox_passgen.setObjectName("spinBox_passgen")
        self.horizontalLayout_3.addWidget(self.spinBox_passgen)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab_passgen)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_passgen_cuc = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_cuc.setObjectName("checkBox_passgen_cuc")
        self.gridLayout.addWidget(self.checkBox_passgen_cuc, 2, 0, 1, 1)
        self.checkBox_passgen_spaces = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_spaces.setObjectName("checkBox_passgen_spaces")
        self.gridLayout.addWidget(self.checkBox_passgen_spaces, 2, 1, 1, 1)
        self.checkBox_passgen_llc = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_llc.setChecked(True)
        self.checkBox_passgen_llc.setObjectName("checkBox_passgen_llc")
        self.gridLayout.addWidget(self.checkBox_passgen_llc, 1, 0, 1, 1)
        self.checkBox_passgen_escape = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_escape.setObjectName("checkBox_passgen_escape")
        self.gridLayout.addWidget(self.checkBox_passgen_escape, 4, 1, 1, 1)
        self.checkBox_passgen_luc = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_luc.setChecked(True)
        self.checkBox_passgen_luc.setObjectName("checkBox_passgen_luc")
        self.gridLayout.addWidget(self.checkBox_passgen_luc, 0, 0, 1, 1)
        self.checkBox_passgen_clc = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_clc.setObjectName("checkBox_passgen_clc")
        self.gridLayout.addWidget(self.checkBox_passgen_clc, 3, 0, 1, 1)
        self.checkBox_passgen_pretty = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_pretty.setObjectName("checkBox_passgen_pretty")
        self.gridLayout.addWidget(self.checkBox_passgen_pretty, 4, 0, 1, 1)
        self.checkBox_passgen_symbols = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_symbols.setObjectName("checkBox_passgen_symbols")
        self.gridLayout.addWidget(self.checkBox_passgen_symbols, 3, 1, 1, 1)
        self.checkBox_passgen_numbers = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_numbers.setChecked(True)
        self.checkBox_passgen_numbers.setObjectName("checkBox_passgen_numbers")
        self.gridLayout.addWidget(self.checkBox_passgen_numbers, 0, 1, 1, 1)
        self.checkBox_passgen_symbols1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_symbols1.setChecked(True)
        self.checkBox_passgen_symbols1.setObjectName("checkBox_passgen_symbols1")
        self.gridLayout.addWidget(self.checkBox_passgen_symbols1, 1, 1, 1, 1)
        self.checkBox_passgen_unique = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_passgen_unique.setObjectName("checkBox_passgen_unique")
        self.gridLayout.addWidget(self.checkBox_passgen_unique, 6, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_passgen_generate = QtWidgets.QPushButton(self.tab_passgen)
        self.pushButton_passgen_generate.setObjectName("pushButton_passgen_generate")
        self.horizontalLayout_2.addWidget(self.pushButton_passgen_generate)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_passgen_clipboard = QtWidgets.QPushButton(self.tab_passgen)
        self.pushButton_passgen_clipboard.setObjectName("pushButton_passgen_clipboard")
        self.horizontalLayout_2.addWidget(self.pushButton_passgen_clipboard)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_passgen, "")
        self.tab_email_checker = QtWidgets.QWidget()
        self.tab_email_checker.setObjectName("tab_email_checker")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_email_checker)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.tab_email_checker)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit_email_checker = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.textEdit_email_checker.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_email_checker.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_email_checker.setObjectName("textEdit_email_checker")
        self.horizontalLayout_4.addWidget(self.textEdit_email_checker)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_email_checker_highlight = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_email_checker_highlight.setObjectName("groupBox_email_checker_highlight")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_email_checker_highlight)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_email_checker_latin = QtWidgets.QCheckBox(self.groupBox_email_checker_highlight)
        self.checkBox_email_checker_latin.setObjectName("checkBox_email_checker_latin")
        self.verticalLayout_5.addWidget(self.checkBox_email_checker_latin)
        self.checkBox_email_checker_cyrillic = QtWidgets.QCheckBox(self.groupBox_email_checker_highlight)
        self.checkBox_email_checker_cyrillic.setObjectName("checkBox_email_checker_cyrillic")
        self.verticalLayout_5.addWidget(self.checkBox_email_checker_cyrillic)
        self.checkBox_email_checker_numbers = QtWidgets.QCheckBox(self.groupBox_email_checker_highlight)
        self.checkBox_email_checker_numbers.setObjectName("checkBox_email_checker_numbers")
        self.verticalLayout_5.addWidget(self.checkBox_email_checker_numbers)
        self.checkBox_email_checker_spaces = QtWidgets.QCheckBox(self.groupBox_email_checker_highlight)
        self.checkBox_email_checker_spaces.setObjectName("checkBox_email_checker_spaces")
        self.verticalLayout_5.addWidget(self.checkBox_email_checker_spaces)
        self.checkBox_email_checker_punctuation = QtWidgets.QCheckBox(self.groupBox_email_checker_highlight)
        self.checkBox_email_checker_punctuation.setObjectName("checkBox_email_checker_punctuation")
        self.verticalLayout_5.addWidget(self.checkBox_email_checker_punctuation)
        self.checkBox_email_checker_emails = QtWidgets.QCheckBox(self.groupBox_email_checker_highlight)
        self.checkBox_email_checker_emails.setObjectName("checkBox_email_checker_emails")
        self.verticalLayout_5.addWidget(self.checkBox_email_checker_emails)
        self.verticalLayout_3.addWidget(self.groupBox_email_checker_highlight)
        self.groupBox_email_checker_edit = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_email_checker_edit.setObjectName("groupBox_email_checker_edit")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_email_checker_edit)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_email_checker_empty = QtWidgets.QCheckBox(self.groupBox_email_checker_edit)
        self.checkBox_email_checker_empty.setObjectName("checkBox_email_checker_empty")
        self.verticalLayout_6.addWidget(self.checkBox_email_checker_empty)
        self.checkBox_email_checker_replace = QtWidgets.QCheckBox(self.groupBox_email_checker_edit)
        self.checkBox_email_checker_replace.setObjectName("checkBox_email_checker_replace")
        self.verticalLayout_6.addWidget(self.checkBox_email_checker_replace)
        self.checkBox_email_checker_no_emails = QtWidgets.QCheckBox(self.groupBox_email_checker_edit)
        self.checkBox_email_checker_no_emails.setObjectName("checkBox_email_checker_no_emails")
        self.verticalLayout_6.addWidget(self.checkBox_email_checker_no_emails)
        self.verticalLayout_3.addWidget(self.groupBox_email_checker_edit)
        self.pushButton_email_checker_clipboard = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_email_checker_clipboard.setObjectName("pushButton_email_checker_clipboard")
        self.verticalLayout_3.addWidget(self.pushButton_email_checker_clipboard)
        self.verticalLayout_4.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_email_checker, "")
        self.tab_other = QtWidgets.QWidget()
        self.tab_other.setObjectName("tab_other")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_other)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_other_mac_format = QtWidgets.QGroupBox(self.tab_other)
        self.groupBox_other_mac_format.setObjectName("groupBox_other_mac_format")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_other_mac_format)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_other_mac_format = QtWidgets.QLineEdit(self.groupBox_other_mac_format)
        self.lineEdit_other_mac_format.setReadOnly(False)
        self.lineEdit_other_mac_format.setObjectName("lineEdit_other_mac_format")
        self.horizontalLayout_5.addWidget(self.lineEdit_other_mac_format)
        self.checkBox_other_mac_format_linux = QtWidgets.QCheckBox(self.groupBox_other_mac_format)
        self.checkBox_other_mac_format_linux.setObjectName("checkBox_other_mac_format_linux")
        self.horizontalLayout_5.addWidget(self.checkBox_other_mac_format_linux)
        self.checkBox_other_mac_format_uppercase = QtWidgets.QCheckBox(self.groupBox_other_mac_format)
        self.checkBox_other_mac_format_uppercase.setObjectName("checkBox_other_mac_format_uppercase")
        self.horizontalLayout_5.addWidget(self.checkBox_other_mac_format_uppercase)
        self.pushButton_other_mac_format_to_clipboard = QtWidgets.QPushButton(self.groupBox_other_mac_format)
        self.pushButton_other_mac_format_to_clipboard.setObjectName("pushButton_other_mac_format_to_clipboard")
        self.horizontalLayout_5.addWidget(self.pushButton_other_mac_format_to_clipboard)
        self.verticalLayout_7.addWidget(self.groupBox_other_mac_format)
        self.groupBox_other_phone_number = QtWidgets.QGroupBox(self.tab_other)
        self.groupBox_other_phone_number.setObjectName("groupBox_other_phone_number")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_other_phone_number)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_other_phone_number = QtWidgets.QLineEdit(self.groupBox_other_phone_number)
        self.lineEdit_other_phone_number.setObjectName("lineEdit_other_phone_number")
        self.horizontalLayout_7.addWidget(self.lineEdit_other_phone_number)
        self.checkBox_other_phone_number = QtWidgets.QCheckBox(self.groupBox_other_phone_number)
        self.checkBox_other_phone_number.setObjectName("checkBox_other_phone_number")
        self.horizontalLayout_7.addWidget(self.checkBox_other_phone_number)
        self.pushButton_other_phone_number_to_clipboard = QtWidgets.QPushButton(self.groupBox_other_phone_number)
        self.pushButton_other_phone_number_to_clipboard.setObjectName("pushButton_other_phone_number_to_clipboard")
        self.horizontalLayout_7.addWidget(self.pushButton_other_phone_number_to_clipboard)
        self.verticalLayout_7.addWidget(self.groupBox_other_phone_number)
        self.groupBox_other_transliteration = QtWidgets.QGroupBox(self.tab_other)
        self.groupBox_other_transliteration.setObjectName("groupBox_other_transliteration")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_other_transliteration)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_other_transliteration = QtWidgets.QLineEdit(self.groupBox_other_transliteration)
        self.lineEdit_other_transliteration.setObjectName("lineEdit_other_transliteration")
        self.verticalLayout_9.addWidget(self.lineEdit_other_transliteration)
        self.label_other_transliteration = QtWidgets.QLabel(self.groupBox_other_transliteration)
        self.label_other_transliteration.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_other_transliteration.setMouseTracking(True)
        self.label_other_transliteration.setTabletTracking(True)
        self.label_other_transliteration.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_other_transliteration.setObjectName("label_other_transliteration")
        self.verticalLayout_9.addWidget(self.label_other_transliteration)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radioButton_other_transliteration_as_is = QtWidgets.QRadioButton(self.groupBox_other_transliteration)
        self.radioButton_other_transliteration_as_is.setChecked(True)
        self.radioButton_other_transliteration_as_is.setObjectName("radioButton_other_transliteration_as_is")
        self.verticalLayout_10.addWidget(self.radioButton_other_transliteration_as_is)
        self.radioButton_other_transliteration_upper = QtWidgets.QRadioButton(self.groupBox_other_transliteration)
        self.radioButton_other_transliteration_upper.setObjectName("radioButton_other_transliteration_upper")
        self.verticalLayout_10.addWidget(self.radioButton_other_transliteration_upper)
        self.radioButton_other_transliteration_lower = QtWidgets.QRadioButton(self.groupBox_other_transliteration)
        self.radioButton_other_transliteration_lower.setObjectName("radioButton_other_transliteration_lower")
        self.verticalLayout_10.addWidget(self.radioButton_other_transliteration_lower)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.pushButton_other_transliteration_to_clipboard = QtWidgets.QPushButton(self.groupBox_other_transliteration)
        self.pushButton_other_transliteration_to_clipboard.setObjectName("pushButton_other_transliteration_to_clipboard")
        self.horizontalLayout_8.addWidget(self.pushButton_other_transliteration_to_clipboard)
        self.verticalLayout_7.addWidget(self.groupBox_other_transliteration)
        self.groupBox_other_ipcalc = QtWidgets.QGroupBox(self.tab_other)
        self.groupBox_other_ipcalc.setObjectName("groupBox_other_ipcalc")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_other_ipcalc)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_other_ipcalc_ipaddr = QtWidgets.QLineEdit(self.groupBox_other_ipcalc)
        self.lineEdit_other_ipcalc_ipaddr.setInputMask("")
        self.lineEdit_other_ipcalc_ipaddr.setObjectName("lineEdit_other_ipcalc_ipaddr")
        self.horizontalLayout_6.addWidget(self.lineEdit_other_ipcalc_ipaddr)
        self.comboBox_other_ipcalc_mask = QtWidgets.QComboBox(self.groupBox_other_ipcalc)
        self.comboBox_other_ipcalc_mask.setObjectName("comboBox_other_ipcalc_mask")
        self.horizontalLayout_6.addWidget(self.comboBox_other_ipcalc_mask)
        self.pushButton_other_ipcalc_calculate = QtWidgets.QPushButton(self.groupBox_other_ipcalc)
        self.pushButton_other_ipcalc_calculate.setObjectName("pushButton_other_ipcalc_calculate")
        self.horizontalLayout_6.addWidget(self.pushButton_other_ipcalc_calculate)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_other_ipcalc_network = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        self.label_other_ipcalc_network.setFrameShape(QtWidgets.QFrame.Box)
        self.label_other_ipcalc_network.setText("")
        self.label_other_ipcalc_network.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_other_ipcalc_network.setObjectName("label_other_ipcalc_network")
        self.gridLayout_2.addWidget(self.label_other_ipcalc_network, 0, 1, 1, 1)
        self.label_other_ipcalc_host_count = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        self.label_other_ipcalc_host_count.setFrameShape(QtWidgets.QFrame.Box)
        self.label_other_ipcalc_host_count.setText("")
        self.label_other_ipcalc_host_count.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_other_ipcalc_host_count.setObjectName("label_other_ipcalc_host_count")
        self.gridLayout_2.addWidget(self.label_other_ipcalc_host_count, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_other_ipcalc_broadcast = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        self.label_other_ipcalc_broadcast.setFrameShape(QtWidgets.QFrame.Box)
        self.label_other_ipcalc_broadcast.setText("")
        self.label_other_ipcalc_broadcast.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_other_ipcalc_broadcast.setObjectName("label_other_ipcalc_broadcast")
        self.gridLayout_2.addWidget(self.label_other_ipcalc_broadcast, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_other_ipcalc_host_min = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        self.label_other_ipcalc_host_min.setFrameShape(QtWidgets.QFrame.Box)
        self.label_other_ipcalc_host_min.setText("")
        self.label_other_ipcalc_host_min.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_other_ipcalc_host_min.setObjectName("label_other_ipcalc_host_min")
        self.gridLayout_2.addWidget(self.label_other_ipcalc_host_min, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_other_ipcalc_host_max = QtWidgets.QLabel(self.groupBox_other_ipcalc)
        self.label_other_ipcalc_host_max.setFrameShape(QtWidgets.QFrame.Box)
        self.label_other_ipcalc_host_max.setText("")
        self.label_other_ipcalc_host_max.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_other_ipcalc_host_max.setObjectName("label_other_ipcalc_host_max")
        self.gridLayout_2.addWidget(self.label_other_ipcalc_host_max, 4, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.verticalLayout_7.addWidget(self.groupBox_other_ipcalc)
        self.tabWidget.addTab(self.tab_other, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.CentralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuLanguage = QtWidgets.QMenu(self.menuOptions)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setCheckable(True)
        self.actionEnglish.setChecked(True)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionRussian = QtWidgets.QAction(MainWindow)
        self.actionRussian.setCheckable(True)
        self.actionRussian.setChecked(False)
        self.actionRussian.setObjectName("actionRussian")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.action_Undo = QtWidgets.QAction(MainWindow)
        self.action_Undo.setObjectName("action_Undo")
        self.action_Redo = QtWidgets.QAction(MainWindow)
        self.action_Redo.setObjectName("action_Redo")
        self.action_Copy_all = QtWidgets.QAction(MainWindow)
        self.action_Copy_all.setObjectName("action_Copy_all")
        self.menuFile.addAction(self.actionQuit)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionRussian)
        self.menuOptions.addAction(self.menuLanguage.menuAction())
        self.menuOptions.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.action_Redo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.checkBox_passgen_luc)
        MainWindow.setTabOrder(self.checkBox_passgen_luc, self.checkBox_passgen_llc)
        MainWindow.setTabOrder(self.checkBox_passgen_llc, self.checkBox_passgen_cuc)
        MainWindow.setTabOrder(self.checkBox_passgen_cuc, self.checkBox_passgen_clc)
        MainWindow.setTabOrder(self.checkBox_passgen_clc, self.checkBox_passgen_pretty)
        MainWindow.setTabOrder(self.checkBox_passgen_pretty, self.checkBox_passgen_unique)
        MainWindow.setTabOrder(self.checkBox_passgen_unique, self.checkBox_passgen_numbers)
        MainWindow.setTabOrder(self.checkBox_passgen_numbers, self.checkBox_passgen_symbols)
        MainWindow.setTabOrder(self.checkBox_passgen_symbols, self.checkBox_passgen_spaces)
        MainWindow.setTabOrder(self.checkBox_passgen_spaces, self.checkBox_passgen_symbols)
        MainWindow.setTabOrder(self.checkBox_passgen_symbols, self.checkBox_passgen_escape)
        MainWindow.setTabOrder(self.checkBox_passgen_escape, self.pushButton_passgen_generate)
        MainWindow.setTabOrder(self.pushButton_passgen_generate, self.pushButton_passgen_clipboard)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AdminTools"))
        self.label_passgen_password.setText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "Length:"))
        self.groupBox.setTitle(_translate("MainWindow", "Characters:"))
        self.checkBox_passgen_cuc.setText(_translate("MainWindow", "Cyrillic upper case"))
        self.checkBox_passgen_spaces.setText(_translate("MainWindow", "Spaces"))
        self.checkBox_passgen_llc.setText(_translate("MainWindow", "Latin lower case"))
        self.checkBox_passgen_escape.setText(_translate("MainWindow", "Escape all symbols"))
        self.checkBox_passgen_luc.setText(_translate("MainWindow", "Latin upper case"))
        self.checkBox_passgen_clc.setText(_translate("MainWindow", "Cyrillic lower case"))
        self.checkBox_passgen_pretty.setText(_translate("MainWindow", "Pretty symbols"))
        self.checkBox_passgen_symbols.setText(_translate("MainWindow", "Cyrillic symbols"))
        self.checkBox_passgen_numbers.setText(_translate("MainWindow", "Numbers"))
        self.checkBox_passgen_symbols1.setText(_translate("MainWindow", "Symbols"))
        self.checkBox_passgen_unique.setText(_translate("MainWindow", "Unique string"))
        self.pushButton_passgen_generate.setText(_translate("MainWindow", "Generate"))
        self.pushButton_passgen_clipboard.setText(_translate("MainWindow", "To clipboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_passgen), _translate("MainWindow", "Password generator"))
        self.groupBox_email_checker_highlight.setTitle(_translate("MainWindow", "Highlight:"))
        self.checkBox_email_checker_latin.setText(_translate("MainWindow", "Latin"))
        self.checkBox_email_checker_cyrillic.setText(_translate("MainWindow", "Cyrillic"))
        self.checkBox_email_checker_numbers.setText(_translate("MainWindow", "Numbers"))
        self.checkBox_email_checker_spaces.setText(_translate("MainWindow", "Spaces"))
        self.checkBox_email_checker_punctuation.setText(_translate("MainWindow", "Punctuation"))
        self.checkBox_email_checker_emails.setText(_translate("MainWindow", "Valid e-mails"))
        self.groupBox_email_checker_edit.setTitle(_translate("MainWindow", "Edit:"))
        self.checkBox_email_checker_empty.setText(_translate("MainWindow", "Remove empty lines"))
        self.checkBox_email_checker_replace.setText(_translate("MainWindow", "Replace cyrillic"))
        self.checkBox_email_checker_no_emails.setText(_translate("MainWindow", "Remove non e-mail"))
        self.pushButton_email_checker_clipboard.setText(_translate("MainWindow", "To clipboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_email_checker), _translate("MainWindow", "E-mail checker"))
        self.groupBox_other_mac_format.setTitle(_translate("MainWindow", "MAC format:"))
        self.lineEdit_other_mac_format.setInputMask(_translate("MainWindow", "HH:HH:HH:HH:HH:HH;_"))
        self.checkBox_other_mac_format_linux.setText(_translate("MainWindow", "Linux"))
        self.checkBox_other_mac_format_uppercase.setText(_translate("MainWindow", "Upper case"))
        self.pushButton_other_mac_format_to_clipboard.setText(_translate("MainWindow", "To clipboard"))
        self.groupBox_other_phone_number.setTitle(_translate("MainWindow", "Phone number normalizer:"))
        self.checkBox_other_phone_number.setText(_translate("MainWindow", "Escape by *"))
        self.pushButton_other_phone_number_to_clipboard.setText(_translate("MainWindow", "To clipboard"))
        self.groupBox_other_transliteration.setTitle(_translate("MainWindow", "Transliteration:"))
        self.label_other_transliteration.setText(_translate("MainWindow", "Result"))
        self.radioButton_other_transliteration_as_is.setText(_translate("MainWindow", "As is"))
        self.radioButton_other_transliteration_upper.setText(_translate("MainWindow", "UPPER CASE"))
        self.radioButton_other_transliteration_lower.setText(_translate("MainWindow", "lower case"))
        self.pushButton_other_transliteration_to_clipboard.setText(_translate("MainWindow", "To clipboard"))
        self.groupBox_other_ipcalc.setTitle(_translate("MainWindow", "IP calculator:"))
        self.pushButton_other_ipcalc_calculate.setText(_translate("MainWindow", "Calculate"))
        self.label_2.setText(_translate("MainWindow", "Network:"))
        self.label_6.setText(_translate("MainWindow", "Host count:"))
        self.label_4.setText(_translate("MainWindow", "Broadcast:"))
        self.label_8.setText(_translate("MainWindow", "Host min:"))
        self.label_10.setText(_translate("MainWindow", "Host max:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_other), _translate("MainWindow", "Other"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.actionRussian.setText(_translate("MainWindow", "Russian"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.action_Undo.setText(_translate("MainWindow", "&Undo"))
        self.action_Redo.setText(_translate("MainWindow", "&Redo"))
        self.action_Copy_all.setText(_translate("MainWindow", "&Copy all"))

